### PR TITLE
Win composite child support (increasing buffer size for interface GUIDs)

### PR DESCRIPTION
**Pull request by Tpimp**
This pull request simply increases the MAX size of the interfaces GUIDs. This fixes the issue where pRegQueryValueExA call for DeviceInterfaceGuids will return ERROR_MORE_DATA. 

see https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regqueryvalueexa for reference

### CODE REVIEW

**Comment by tormodvolden** [comment]
I think you wanted to merge this into the jdkvision:win-composite-child-support branch and not master but that is not a problem.

The GUID character array is limited to 40 characters because a GUID is a 128-bit UUID written out in 32 hex characters and 4 hyphens, and from Windows, 2 braces and possibly a terminating zero or two (see #927).

Is this a case where multiple GUIDs are received? I think the code is not prepared for that.

**Comment by Tpimp** [comment]
> I think you wanted to merge this into the jdkvision:win-composite-child-support branch and not master but that is not a problem.
> 
> The GUID character array is limited to 40 characters because a GUID is a 128-bit UUID written out in 32 hex characters and 4 hyphens, and from Windows, 2 braces and possibly a terminating zero or two (see [libusb#927](https://github.com/libusb/libusb/pull/927)).
> 
> Is this a case where multiple GUIDs are received? I think the code is not prepared for that.

Sorry for the late reply. My device actual returns the error ERROR_MORE_DATA (Error code 234) @ [Line 1652](https://github.com/jdkvision/libusb/blob/6a61f2a1c22621504de009302bfc465ff151156e/libusb/os/windows_winusb.c#L1652) . 

Setting the max size to 80 allows my device to work (as the size for the [NZXT KrakenZ73](https://nzxt.com/product/kraken-z73) interface 0 returned is **79**). Normally the correct solution would be to resize the array dynamically when the error is received and then try again. However there are quite a few code changes required to allow dynamic GUID array lengths as opposed to the extra 40 characters per device.

**Comment by tormodvolden** [comment]
Just so we don't misunderstand each other: A GUID shouldn't be longer than 40 characters (possible wide characters). So what do you receive in this case? Line 1652 is also the "DeviceInterfaceGUID" (singular) call so we'd expect one single GUID back.

I believe you that setting max size to 80 make your device work. But without knowing why, we don't know what is exactly the correct solution.

**Comment by Tpimp** [comment]
Sorry line number was off and the buffer size needs to be larger, not the size of a GUID. Yes it returns 2 GUIDS from DeviceInterfaceGUIDS and overflows the buffer. I agree, we can ignore setting the max size to 80 and instead I'll do a pull request on libusb adding dynamic DeviceInterfaceGUIDS retrieval so it can handle reading more than one interface GUID from the registry. That will solve the issue "correctly". Thanks for your feedback.

**Comment by tormodvolden** [comment]
Great, thanks. Yeah, if we for some reason can get two GUIDs back, we can get three back also for what I know.

**Comment by tormodvolden** [comment]
Which are the two GUIDs that you receive in this case? Just wonder how often this happens. libusb only dealt with one GUID returned (or the first one?) since the beginning.

**Comment by Tpimp** [comment]
It seems like an error on the device manufacturer fw/inf as the two GUIDS are the same. Still, it wouldn't hurt to add support for reading X number of interfaces GUIDs. I will still check that we don't add existing GUIDs and the erroneous copy will be dropped so it should work for this (error) case and legitimate device interfaces with multiple GUIDs.

**Comment by tormodvolden** [comment]
Well, if it is only for broken devices we could alternatively just treat ERROR_MORE_DATA as success and ignore any further GUIDs, without adding more code. But if there are legitimate cases of multiple GUIDs your suggestion will be best.

Example:
```
diff --git a/libusb/os/windows_winusb.c b/libusb/os/windows_winusb.c
index df40773..b957490 100644
--- a/libusb/os/windows_winusb.c
+++ b/libusb/os/windows_winusb.c
@@ -1628,7 +1628,8 @@ static int winusb_get_device_list(struct libusb_context *ctx, struct discovered_
                                pRegCloseKey(key);
                                if (s == ERROR_FILE_NOT_FOUND) {
                                        break; /* no DeviceInterfaceGUID registered */
-                               } else if (s != ERROR_SUCCESS) {
+                               /* if multiple GUIDs only consider the first */
+                               } else if (s != ERROR_SUCCESS && s != ERROR_MORE_DATA) {
                                        usbi_warn(ctx, "unexpected error from pRegQueryValueExA for '%s'", dev_id);
                                        break;
                                }

```

**Comment by Tpimp** [comment]
Seems like the correct fix is the one I implemented that will handle extra GUIDs. But this might be what the developers would prefer to do? Sorry I didn't get mine in as a PR I have been busy today.

**Pull request closed without merging**
